Consolidated_App/Models/FramworkModels/MenuItem.cs
namespace Consolidated_App.Models.FramworkModels
{
    public class MenuItem
    {
        public string SystemName { get; set; }

        public string Title { get; set; }

        public string ControllerName { get; set; }

        public string ActionName { get; set; }

        public RouteValueDictionary RouteValues { get; set; }

        public string Url { get; set; }

        public IList<MenuItem> ChildNodes { get; set; }

        public string IconClass { get; set; }

        public bool Visible { get; set; }

        public bool OpenUrlInNewTab { get; set; }
    }
}

Consolidated_App/Controllers/ActivityReportController.cs
using System.Diagnostics;
using CNET_V7_Domain.Domain.ViewSchema;
using CNET_V7_Domain.Misc;
using Consolidated_App.Models;
using Consolidated_App.WebConstants;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Mvc;

namespace Consolidated_App.Controllers
{
    public class ActivityReportController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly SharedHelpers _sharedHelpers;
        public ActivityReportController(ILogger<HomeController> logger,
             SharedHelpers sharedHelpers)
        {
            _logger = logger;
            _sharedHelpers = sharedHelpers;
        }

        public IActionResult Index()
        {
            return View(new ConsolidateActivitySearchModel { uploadDate = DateTime.Now.ToString() + "-" + DateTime.Now.ToString() });
          
        }

        [HttpGet]
        public async Task<object> GetDocumentList_Activity(DataSourceLoadOptions loadOptions, ConsolidateModel searchModel)
        {
            var testx = await GetAllSalesReport_Acivity(searchModel);

            return DataSourceLoader.Load(testx, loadOptions);
        } 
        
        [HttpGet]
        public async Task<object> GetDocumentList_Activity_Detail(DataSourceLoadOptions loadOptions, ConsolidateModel searchModel)
        {
            var testx = await GetAllSalesReport_Acivity_Detail(searchModel);

            return DataSourceLoader.Load(testx, loadOptions);
        }

        [HttpPost]
        public virtual async Task<IActionResult> getDocumentsList_Activity(ConsolidateActivitySearchModel searchModel)
        {
            if (searchModel == null)
            {
                return BadRequest("Please set a valid search criteria!");
            }

            return PartialView("_consolidateActivityGrid", searchModel);

        }
        public async Task<List<CNET_V7_Domain.Misc.ConsolidateActivityResult>> GetAllSalesReport_Acivity(ConsolidateModel searchModel)
        {
            Dictionary<string, string> Dictionaryvalue = new Dictionary<string, string>();
            var issuedDateRange = GeneralHelpers.parseDateRange(searchModel.uploadDate);
            if (issuedDateRange == null)
            {
                issuedDateRange = new DateRange();
                issuedDateRange.startDate = DateTime.Now.AddYears(-22);
                issuedDateRange.endDate = DateTime.Now.AddYears(-22);
            }
            if (issuedDateRange?.startDate != null)
                Dictionaryvalue.Add("startDate", issuedDateRange?.startDate?.ToString());
            if (issuedDateRange?.endDate != null)
                Dictionaryvalue.Add("endDate", issuedDateRange?.endDate?.ToString());
           
            try
            {
                var report = await _sharedHelpers.GetFilterDynamicData<ResponseModel<List<CNET_V7_Domain.Misc.ConsolidateActivityResult>>>("cnetReport/consolidation_activity_summary", Dictionaryvalue);
                if (report.Success)
                {
                    return report.Data;
                }
                else
                {
                    return new List<CNET_V7_Domain.Misc.ConsolidateActivityResult>();
                }

            }
            catch
            {
                return new List<CNET_V7_Domain.Misc.ConsolidateActivityResult>();
            }
        }
        public async Task<List<CNET_V7_Domain.Misc.ActivityDetailResult>> GetAllSalesReport_Acivity_Detail(ConsolidateModel searchModel)
        {
            Dictionary<string, string> Dictionaryvalue = new Dictionary<string, string>();
            var issuedDateRange = GeneralHelpers.parseDateRange(searchModel.uploadDate);
            if (searchModel.uploadDate == null)
            {
                issuedDateRange = new DateRange();
                issuedDateRange.startDate = DateTime.Now.AddYears(-22);
                issuedDateRange.endDate = DateTime.Now.AddYears(-22);
            }
            if (issuedDateRange?.startDate != null)
                Dictionaryvalue.Add("startDate", issuedDateRange?.startDate?.ToString());
            if (issuedDateRange?.endDate != null)
                Dictionaryvalue.Add("endDate", issuedDateRange?.endDate?.ToString());
            if (searchModel?.Distributor != null)
                Dictionaryvalue.Add("distributer", searchModel?.Distributor?.ToString());

            try
            {
                var report = await _sharedHelpers.GetFilterDynamicData<ResponseModel<List<CNET_V7_Domain.Misc.ActivityDetailResult>>>("cnetReport/activity_detail_list", Dictionaryvalue);

                if (report.Success)
                {
                    return report.Data;
                }
                else
                {
                    return new List<CNET_V7_Domain.Misc.ActivityDetailResult>();
                }

            }
            catch
            {
                return new List<CNET_V7_Domain.Misc.ActivityDetailResult>();
            }
        }
    }
}

Consolidated_App/Controllers/EcommerceReportController.cs
using System.Diagnostics;
using Consolidated_App.Models;
using Microsoft.AspNetCore.Mvc;

namespace Consolidated_App.Controllers
{
    public class EcommerceReportController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public EcommerceReportController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Consolidated_App/Controllers/MassUpdateController.cs
using System.Collections.Generic;
using System.Diagnostics;
using CNET_V7_Domain.Domain.Hrms;
using CNET_V7_Domain.Misc.ThirdParty;
using CNET_V7_Domain;
using Consolidated_App.Models;
using Microsoft.AspNetCore.Mvc;
using NPOI.SS.UserModel;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;
using CNET_V7_Domain.Domain.ArticleSchema;
using CNET_V7_Domain.Misc.PmsDTO;
namespace Consolidated_App.Controllers
{
    public class MassUpdateController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public MassUpdateController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> ImportExcelCount(MassUpdateForImport exCount)
        {
            if (string.IsNullOrEmpty(exCount?.distributorID))
            {
                TempData["errorData"] = "Please Select Distributor First!";
                return RedirectToAction("Index");
            }

            if (exCount?.fileUpload == null || exCount.fileUpload.Length == 0)
            {
                return Content("<center><span style='height:30px;line-height:30px;padding: 0px 15px;' class='alert alert-danger'>Invalid Excel File!</span></center>");
            }

            IFormFile file = exCount.fileUpload;
            string fileName = file.FileName;
            string sFileExtension = Path.GetExtension(fileName).ToLower();

            if (sFileExtension != ".xls" && sFileExtension != ".xlsx" && sFileExtension != ".csv" && sFileExtension != ".xlsm" && sFileExtension != ".xlsb")
            {
                return Content("<center><span style='height:30px;line-height:30px;padding: 0px 15px;' class='alert alert-danger'>Invalid Excel File!</span></center>");
            }

            List<ImportedCustomerModel> importedCustomers = new List<ImportedCustomerModel>();
            using (var stream = new MemoryStream())
            {
                file.CopyTo(stream);
                stream.Position = 0;

                ISheet sheet;
                if (sFileExtension == ".xls")
                {
                    HSSFWorkbook hssfwb = new HSSFWorkbook(stream);
                    sheet = hssfwb.GetSheetAt(0);
                }
                else
                {
                    XSSFWorkbook hssfwb = new XSSFWorkbook(stream);
                    sheet = hssfwb.GetSheetAt(0);
                }

                IRow headerRow = sheet.GetRow(0);
                int cellCount = headerRow?.LastCellNum ?? 0;

                for (int i = sheet.FirstRowNum + 1; i <= sheet.LastRowNum; i++)
                {
                    IRow row = sheet.GetRow(i);
                    if (row == null || row.LastCellNum != 11) continue;

                    var data = new ImportedCustomerModel
                    {
                        organizationID = row.GetCell(0)?.ToString(),
                        organizationName = row.GetCell(1)?.ToString(),
                        parentCategory = row.GetCell(3)?.ToString(),
                        category = row.GetCell(4)?.ToString(),
                        tin = row.GetCell(5)?.ToString(),
                        city = row.GetCell(6)?.ToString(),
                        telephone = row.GetCell(7)?.ToString(),
                        street = row.GetCell(8)?.ToString(),
                        latitude = double.TryParse(row.GetCell(9)?.ToString(), out double lat) ? lat : 0,
                        longitude = double.TryParse(row.GetCell(10)?.ToString(), out double lng) ? lng : 0,
                    };

                    importedCustomers.Add(data);
                }
            }

            TempData["successData"] = "Updated!";
            var importResults = new MassUpdateForImport
            {
                ExcelCountList = importedCustomers,
                distributorName = exCount.distributorName
            };

            return View("Index", importResults);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Consolidated_App/Controllers/PriceUpdateController.cs
using System.Diagnostics;
using CNET_V7_Domain.Domain.CommonSchema;
using CNET_V7_Domain.Domain.TransactionSchema;
using CNET_V7_Domain.Domain.ViewSchema;
using CNET_V7_Domain.Misc;
using Consolidated_App.Models;
using Consolidated_App.WebConstants;
using Microsoft.AspNetCore.Mvc;

namespace Consolidated_App.Controllers
{
    public class PriceUpdateController : Controller
    {
        private Consolidated_App.AuthNavigation.AuthenticationManager _authenticationManager;
        private readonly ILogger<HomeController> _logger;
        private readonly SharedHelpers _sharedHelpers;
        int loggedUser = 0;
        int currentConsigneeUnit = 0;
        public PriceUpdateController(ILogger<HomeController> logger,
             SharedHelpers sharedHelpers,
             AuthNavigation.AuthenticationManager authenticationManager)
        {
            _logger = logger;
            _sharedHelpers = sharedHelpers;
            _authenticationManager = authenticationManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GetArticlesByDistributor([FromBody] DistributorRequest request)
        {
            var articles = new List<ArticlePriceUpdateResponse>();
            Dictionary<string, string> Dictionaryvalue = new Dictionary<string, string>();
            Dictionaryvalue.Add("distributer", request?.Distributor?.ToString());
            
            var articleUpdates2 = new List<ArticlePriceUpdateResponse>();
            var report = await _sharedHelpers.GetFilterDynamicData<ResponseModel<List<ArticlePriceUpdateResponse>>>("cnetReport/get_articles_by_distributer", Dictionaryvalue);
            if(report != null && report.Success)
            {
                articleUpdates2 = report.Data.ToList();
            }
          
            foreach (var article in articleUpdates2)
            {
                var articleUpdate = new ArticlePriceUpdateResponse
                {
                    ArticleId = article.ArticleId,
                    Name = article.Name.ToString(),
                    Code = article.Code.ToString(),
                   
                };
                articles.Add(articleUpdate);
            }
            return Json(new { articles });
        }

        [HttpPost]
        public async Task<IActionResult> SaveArticlePrices([FromBody] SaveArticlesRequest request)
        {
            
            await currentUserAndUnit();
            request.Branch = 3;
            request.User = loggedUser;
            var response = await saveupdatedArticleValues(request);
            if (response != null && response.Success)
            {
                return Json(new
                {
                    success = true,
                    message = "Article prices updated successfully!"
                });
            }

            return Json(new
            {
                success = false,
                message = "Failed to update article prices. Please try again."
            });
        }

        public async Task<ResponseModel<SavedArticlePriceResponse>> saveupdatedArticleValues(SaveArticlesRequest postVoucherBuffer)
        {
            var xSavedResult = await _sharedHelpers.SendReqAsync<SaveArticlesRequest, ResponseModel<SavedArticlePriceResponse>>("cnetReport/save_article_price", HttpMethod.Post, postVoucherBuffer);
            return xSavedResult;
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        private async Task currentUserAndUnit()
        {
            var authUser = await _authenticationManager.GetAuthenticatedUser();
            if (authUser != null)
            {
                loggedUser = authUser.Id;
            }
        }
    }
    public class ArticlePriceUpdateResponse2
    {
        public int ArticleId { get; set; }

        public string Name { get; set; }

        public string Code { get; set; }

        public decimal SelfPrice { get; set; }
        public decimal DeliveryPrice { get; set; }
    }
    public class SaveArticlesRequest2
    {
        public string Distributer { get; set; }

        public int Branch { get; set; }

        public List<ArticlePriceUpdateResponse2> UpdatedArticles { get; set; }
    }
}

Consolidated_App/Views/Shared/Menu.cshtml
@using Consolidated_App.Models.FramworkModels
@using Consolidated_App.WebConstants
@using Cnetv7BufferHolder
@using CNET_V7_Domain.Domain.SecuritySchema
@inject Consolidated_App.Common.AuthNavigation.NavigatorManager navigationManager
@inject Consolidated_App.WebConstants.SharedHelpers sharedHelpers
@inject Consolidated_App.AuthNavigation.AuthenticationManager authenticationManager

@{
    var authedUser = await authenticationManager.GetAuthenticatedUser();
    GlobalParamsModel unorderedNavList = await sharedHelpers.GetGlobalParams(authedUser);
    var userRole = await sharedHelpers.GetUserRoleM(authedUser?.Id ?? 0);
    var rootNode = await navigationManager.PrepareNavigationList(unorderedNavList?.navigatorList);
    var _r = userRole?.Role ?? 0;
    var _r1 = authedUser?.Id ?? 0;

    var roleFunctions = GeneralBufferHolder.FunctionWithAccessMatrix
        .Where(u => u.VisuaCompDesc == "Heineken System Management Access"
                 && u.Role.HasValue
                 && u.Role.Value == _r)
        .ToList();
    bool hasMassUpdate = roleFunctions.Any(f => f.Description == "Mass Update" && f.Access == true);
    bool hasOutletTransfer = roleFunctions.Any(f => f.Description == "Outlet Transfer" && f.Access == true);
    bool hasPriceManagement = roleFunctions.Any(f => f.Description == "Price Management" && f.Access == true);
    var reportAccess = await GetReportsWithAccess(_r1);

    bool hasConsolidatedReport = reportAccess?.Any(f => f.DefaultName == "Consolidated Report" && f.Access == true) ?? false;
    bool hasActivityReport = reportAccess?.Any(f => f.DefaultName == "Activity Report" && f.Access == true) ?? false;
    bool hasStockConsolidationReport = reportAccess?.Any(f => f.DefaultName == "Stock Consolidation Report" && f.Access == true) ?? false;
    bool hasCommerceReport = reportAccess?.Any(f => f.DefaultName == "Heineken E-Commerce Report" && f.Access == true) ?? false;
    bool hasOrderManagementReport = reportAccess?.Any(f => f.DefaultName == "Order Management Report" && f.Access == true) ?? false;

    async Task<List<ReportAccessDTO>> GetReportsWithAccess(int userId)
    {
        var userRole = await sharedHelpers.GetUserRoleM(userId);
        if (userRole == null || userRole.Role <= 0)
            return new List<ReportAccessDTO>();

        var xReports = await sharedHelpers.GetReportsBySubSystem();
        if (xReports == null || !xReports.Any())
            return new List<ReportAccessDTO>();

        var xAccess = await sharedHelpers.GetAccessM(userRole.Role);
        if (xAccess == null || !xAccess.Any())
            return new List<ReportAccessDTO>();
        var reportsWithAccess = xReports
            .Where(report => xAccess.Any(access => access.Reference == report.Id.ToString()))
            .Select(report => new ReportAccessDTO
                    {
                        DefaultName = report.DefaultName,
                        Access = true
                    })
            .ToList();

        return reportsWithAccess;
    }
}

<ul class="sidebar-menu" data-widget="tree">
    <li class="active">
        <a href="@Url.Action("Index","Home")">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
    </li>

    <li class="treeview">
        <a href="#">
            <i class="fa fa-cloud"></i> <span>Consolidated Reports</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li>
                @if (hasConsolidatedReport){
                    <a href="@Url.Action("Index","ConsolidatedReport")">
                        <i class="fa fa-dot-circle-o"></i> Sales Report
                    </a>
                }
            
            </li>
            <li>
                @if (hasActivityReport){
                    <a href="@Url.Action("Index","ActivityReport")">
                        <i class="fa fa-dot-circle-o"></i> Activity Report
                    </a>

                }
            </li>
            <li>
                @if (hasStockConsolidationReport){
                    <a href="@Url.Action("Index","StockConsolidationReport")">
                        <i class="fa fa-dot-circle-o"></i> Consolidated Stock Report
                    </a>
                }
               
            </li>
            <li>
                @if (hasCommerceReport){
                    <a href="@Url.Action("Index","EcommerceReport")">
                        <i class="fa fa-dot-circle-o"></i> E-Commerce Integrated Report
                    </a>
                }
               
            </li>
            <li>
                @if (hasOrderManagementReport){
                    <a href="@Url.Action("Index","OrderManagement")">
                        <i class="fa fa-dot-circle-o"></i> Order Management Report
                    </a>
                }
             
            </li>

            @if (hasMassUpdate)
            {
                <li>
                    <a href="@Url.Action("Index","MassUpdate")">
                        <i class="fa fa-dot-circle-o"></i> Mass Update
                    </a>
                </li>
            }
            @if (hasOutletTransfer)
            {
                <li>
                    <a href="@Url.Action("Index","OutleteTransfer")">
                        <i class="fa fa-dot-circle-o"></i> Transfer Outlet
                    </a>
                </li>
            }
            @if (hasPriceManagement)
            {
                <li>
                    <a href="@Url.Action("Index","PriceUpdate")">
                        <i class="fa fa-dot-circle-o"></i> Price Update
                    </a>
                </li>
            }
        </ul>
    </li>
</ul>

Consolidated_App/Views/Shared/_MenuItem.cshtml
@model MenuItem
@using Consolidated_App.Models.FramworkModels
@{

    var hasChildNodes = Model.ChildNodes != null && Model.ChildNodes.Any();
    var liCssClass = "";
    if (hasChildNodes)
    {
        liCssClass = "treeview";
    }

    @functions
    {
        string GetUrl(MenuItem dataUrl)
        {
            if (dataUrl.ChildNodes?.Count > 0)
            {
                return "#";
            }
            else
            {
                return !string.IsNullOrEmpty(dataUrl?.ActionName) && !string.IsNullOrEmpty(dataUrl.ControllerName)
                            ? Url.Action(dataUrl.ActionName, dataUrl.ControllerName, dataUrl.RouteValues)
                            : !string.IsNullOrEmpty(dataUrl.Url)
                            ? $"{(dataUrl.Url.StartsWith("~/", StringComparison.Ordinal) ? Url.Content(dataUrl.Url) : dataUrl.Url).TrimEnd('/')}"
                            : string.Empty;
            }
        }
    }

    <li @(!String.IsNullOrEmpty(liCssClass) ? Html.Raw("class=\"" + liCssClass + "\"") : null)>
        <a href="@GetUrl(Model)">
            @if (!string.IsNullOrEmpty(Model.IconClass))
            {
                <text>
                    <i class="fa @Url.Content(Model.IconClass)"></i>
                </text>
            }
            <span>@Model.Title</span>
            @if (hasChildNodes)
            {
                <i class="fa fa-angle-left pull-right"></i>
            }
        </a>
        @if (hasChildNodes)
        {
            <ul class="treeview-menu">
                @foreach (var childItem in Model.ChildNodes)
                {
                    @await Html.PartialAsync("_MenuItem", childItem)

                }


            </ul>
        }
    </li>

}